### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by gerneio** [Softanics/BlazorAppObfuscationDemo#1]
Running the demo blazor app as-is is misleading. The DLL's downloaded to the browser (debug, release, or published) will be the original DLL's and can be downloaded and viewed with normal decompiling tools w/o issue. If you build and then copy the DLL's over the one's served in "wwwroot\\_framework\\_bin", then you will run against issues with Blazor's integrity checking. Setting the two following CSPROJ options helped get past this issue.

```
<PropertyGroup>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
    <BlazorEnableCompression>false</BlazorEnableCompression>
</PropertyGroup>
```
However for a proper release, you'll probably want to figure out how to obfuscate and inject these DLL's at the right point, prior to the Blazor build process. Afterwards, NOW if you load up this demo app in the browser, view the network trace, and download & open the DLL's in a decompiler, you will see they are obfuscated, and the app demo app does appear to function.

Unfortunately, this does not appear to work with the latest Blazor framework updates (.NET 6.0) and in a "typical" project structure with shared libs. Seeing the following error in the browser console on application load.

```
System.AggregateException: One or more errors occurred. (The type initializer for '<Module>' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.PlatformNotSupportedException: System.Diagnostics.Process is not supported on this platform.
   at System.Diagnostics.Process.GetCurrentProcess()
   at <Module>.GetTypeArrayMCMkeysNoFault()
   at <Module>..cctor()
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IMyAppService](IServiceProvider provider)
```

In this case it is blowing up on "provider.GetRequiredService&lt;IMyAppService&gt;()" in Program.cs, in which the requested service is in a shared project that is NOT obfuscated, but the services it relies in (in it's constructor) are in another shared lib that ARE obfuscated. The underlying culprit seems to be the addition of the following method in the obfuscated library, which is def not part of my code:

```
public static Process GetTypeArrayMCMkeysNoFault()
{
	return Process.GetCurrentProcess();
}
```

Since it calls "System.Diagnostics.Process" which is not supported in Blazor WASM, probably due to browser restrictions, this will probably always fail. The demo app probably works (after the previously mentioned tweaks) because it's on an previous version of WASM and/or the obfuscated code never actually ends up calling "System.Diagnostics.Process" (even though it is shown in places when looking at the decompiled code).

**Comment by ArtemRazin** [comment]
@gerneio sure, let me check on my side. I can be a bit slow this week, but I will definitely check this case ASAP.

**Comment by ArtemRazin** [comment]
@gerneio we've finally fixed it in https://www.armdot.com/changelog.html#2022.6 and in https://github.com/Softanics/BlazorAppObfuscationDemo/commit/b023e9732d2f51c07a9aea8ac7d291d7877379e4. It is interesting that it worked with earlier version of .NET!

**Comment by gerneio** [comment]
Do we still need to enable these csproj props, or was that part fixed too?

`<PropertyGroup>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
    <BlazorEnableCompression>false</BlazorEnableCompression>
</PropertyGroup>`
